### PR TITLE
Add option to keep file extension in the share link

### PR DESCRIPTION
**Pull request by Uwy**
For some reasons I had to keep the file extension in the share links so it wouldn't break a client side third party library

I added `keepFileExtension : false` to the configuration thus keeping the default behavior so it shouldn't produce breaking changes

The added file extension check for the urls is fairly simple and might need improvement like options or multiple extensions like `.tar.gz`

### CODE REVIEW

**Comment by silverwind** [comment]
> it wouldn't break a client side third party library

Which one? The original filename (and extension) is communicated in the `Content-Dispostion` header which is a pretty standard way of communicating the filename and well supported by browsers. If you just append the extension, the filename will still be lost, which isn't ideal. If there are other mechanisms that would allow that library to properly detect the filename, we could implement that as well.

**Comment by Uwy** [comment]
I use `markdown-it` client side with a lot of various plugins and [markdown-it-html5-embed](https://github.com/cmrd-senya/markdown-it-html5-embed) is one of them uses the link's extension to determine if it should render a `video`, `audio` or the default `img` tag.

Making http requests while processing a markdown source is not a clean solution, I could also write a plugin to force the user to specify if the link is a video or audio by using somekind of `html5video` syntax, it sounds less convenient.

I just took the least resistance path

**Comment by silverwind** [comment]
Ah, I see, the tool tries to guess the mime type from the URL. Well I think I'd consider something like you did. Can you just clean up the files included in this commit? There's a lot of unneccesary mode changes if you check https://github.com/silverwind/droppy/pull/337/files.

**Comment by Uwy** [comment]
Oh yeah, it was file permissions changes due to some smb share hazard, it should be better now

**Comment by dentm42** [comment]
This would also be helpful for using droppy as a repo for large audio/video files and linking them into WordPress which also uses the file extension as part of it's mechanism to determine what player to use.

**Comment by silverwind** [comment]
Implemented with a few improvments like retroactive links and that link work regardless whether a extension as given or not.

**Comment by Uwy** [comment]
Thank you !

**Pull request closed without merging**
